name: Monthly Rent Reminder

on:
  schedule:
    - cron: "30 16 02 * *"   # Runs every month on 12th at 10:00 AM IST
  workflow_dispatch:        # allows manual run

jobs:
  send_rent_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requests
        run: pip install requests pytz
      - name: Run script
        env:
          WHAPI_TOKEN: ${{secrets.WHAPI_TOKEN}}
          GROUP_ID: ${{secrets.GROUP_ID}}
          MENTION_WAID: ${{secrets.MENTION_WAID}}
        run: python send_message.py
