name: Monthly Rent Reminder

on:
  schedule:
    - cron: "30 14 02 * *"   # 10:00 IST on day 12 every month
  workflow_dispatch:        # manual trigger button

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests python-dotenv pytz

    - name: Run bot
      env:
        WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
        MENTION_WAID: ${{ secrets.MENTION_WAID }}
      run: python send_message.py
